### ISSUE TITLE
信道发生错误： Object {code: 1001, message: "连接信道服务失败，网络错误或者信道服务没有正确响应", detail: Object}

### ISSUE THREAD

**Issue by gaoshanyu** [tencentyun/wafer-client-sdk#5]
连不上：

// 创建信道，需要给定后台服务地址
        var tunnel = new qcloud.Tunnel("https://59431301.qcloud.la/tunnel");

**Comment by nieyin** [comment]
我的也连不上

**Comment by Devin001** [comment]
我也有这个问题

**Comment by techird** [comment]
请排查网络连通问题，确保服务器收到了请求。服务器如果日志有表示收到了请求，再跟踪日志是否正确响应。

**Comment by sammylp** [comment]
我也出现了类似问题
